const briefStore = [
  {
    jobType: "design",
    brandName: "gphics Design",
    brandServices: ["Graphics Design"],
    brandContact: 8165607828,
    brandColors: ["#EE4036", "#262261", "FAAF40"],
    brandValues: ["Unique", "Best"],
    brandEmail: "abdulbasitabdulakeem234@gmail.com",
    brandLocation: "Ogun State, Nigeria",
    brandDescription: `Gphics Design is a design studio that focuses on the design of visual identities and also rebranding.`,
    jobDescription: `We want you to design a unique logo that shows modernity`,
    brandVisuals: [],
    // client
    clientContact: 9077585224,
    clientName: "Abdulbasit",
    clientEmail: "abdulbasitabdulakeem234@gmail.com",
    clientLocation: "Ogun State, Nigeria",
  },
  {
    jobType: "design",
    brandName: "HiConnect",
    brandServices: ["Data Subscription"],
    brandContact: 8165607828,
    brandColors: [" #FFFF00", "#000000"],
    brandValues: ["Connect", "Available"],
    brandEmail: "abdulbasitabdulakeem234@gmail.com",
    brandLocation: "Ogun State, Nigeria",
    brandDescription: `HiConnect is a brand that sells data subscriptions for all networks at an affordable price. We aim to promote connection and love between you and your loved ones throughout the world.`,
    jobDescription: `We want you to design a unique logo that tells our customers we are here to connect them to the entire world`,
    brandVisuals: [],
    // client
    clientContact: 9077585224,
    clientName: "Abdulbasit",
    clientEmail: "abdulbasitabdulakeem234@gmail.com",
    clientLocation: "Ogun State, Nigeria",
  },
  {
    jobType: "design",
    brandName: "Chiral",
    brandServices: ["Visual Identity Design", "Software Development"],
    brandContact: 8165607828,
    brandColors: [" #FF00FF", "#06061B"],
    brandValues: ["Unique", "Outstanding"],
    brandEmail: "abdulbasitabdulakeem234@gmail.com",
    brandLocation: "Ogun State, Nigeria",
    brandDescription: `Chiral is a brand that focus on the design of visual identities for brands and development of softwares. Our aim is to standout amidst the crowd of competitors.`,
    jobDescription: `We want you to design a unique logo that suits our brand description. Remember, we want to be unique.`,
    brandVisuals: [],
    // client
    clientContact: 9077585224,
    clientName: "Abdulbasit",
    clientEmail: "abdulbasitabdulakeem234@gmail.com",
    clientLocation: "Ogun State, Nigeria",
  },
  {
    jobType: "design",
    brandName: "King's Fashion",
    brandServices: ["Tailoring", "Clothe Design"],
    brandContact: 9133146567,
    brandColors: ["#5805CE", "000000"],
    brandValues: ["Royality", "Creative", "Quality Delivery"],
    brandEmail: "N/A",
    brandLocation: "Oyo State, Nigeria",
    brandDescription: `King's Fashion is a textile brand that focuses on the design of both Nigeria Native dress and Western dress. We aim to making you feel the aura of royalty by giving you a quality, unique and eye-pleasing clothe design. `,
    jobDescription: `We want you to design for us a unique logo aiming at royalty.`,
    brandVisuals: [],
    // client
    clientContact: 9133146567,
    clientName: "Uthman",
    clientEmail: "N/A",
    clientLocation: "Oyo State, Nigeria",
  },
  {
    brandName: "Reldrop",
    jobType: "design",
    brandServices: ["Logistics & Delivery"],
    brandContact: 0,
    brandColors: ["#011B33", "09A5DB"],
    brandValues: ["Fast Delivery", "Integrity"],
    brandEmail: "N/A",
    brandLocation: "N/A",
    brandDescription: `A delivery company that utilize complex algorithm to solve logistical issues`,
    jobDescription: `We want you to craft a unique logo for us that would make us unique among competitors `,
    brandVisuals: [],
    // client
    clientContact: 0,
    clientName: "Ali",
    clientEmail: "N/A",
    clientLocation: "N/A",
  },
  {
    brandName: "Sandy",
    jobType: "design",
    brandServices: ["Fashion Design"],
    brandContact: 0,
    brandColors: ["#EDE324", "#000000"],
    brandValues: [],
    brandEmail: "N/A",
    brandLocation: "N/A",
    brandDescription: `We are a fashion company that sells timeless menswear. Our items are made with unique attention to detail and are sold online only. We want to convey a sense of security while at the same rime being professional. `,
    jobDescription: `You must create a logo using using the information given in this brief. They would prefer a mascot logo that uses the color yellow, an iconic logo is also preferable. The logo will be embroided on uniforms. Take into account the company's values and preferences and make sure it will work for the planned use-cases`,
    brandVisuals: [],
    // client
    clientContact: 0,
    clientName: "Sandy Man",
    clientEmail: "N/A",
    clientLocation: "N/A",
  },
  {
    jobType: "design",
    brandName: "Silver Tadpole",
    brandServices: ["Payment"],
    brandContact: 0,
    brandColors: [],
    brandValues: ["Innovative", "Scientific Discovery"],
    brandEmail: "N/A",
    brandLocation: "N/A",
    brandDescription: `We are a company that develops new ways to make payments by combining innovative software with a friendly face. Our main product is a website that you can use wherever you are and implements years of scientific discovery. Our target audience is millenials. We want to convey a sense of victory, while at the same time being kind.`,
    jobDescription: `You must create a logo using the information given in this brief. The logo will be printed on the side of vehicles. Purple color would be prefered. Take into account the company's values and preferences and make sure it will work for the planned use-cases`,
    brandVisuals: [],
    // client
    clientContact: 0,
    clientName: "Silver Tadpole",
    clientEmail: "N/A",
    clientLocation: "N/A",
  },
  {
    jobType: "software",
    brandName: "Feed-master",
    brandServices: ["Feed Formulation"],
    brandContact: 0,
    brandColors: ["green"],
    brandValues: ["Accuracy", "Fast", "Efficient"],
    brandEmail: "N/A",
    brandLocation: "N/A",
    brandDescription: `We are a company that deals with the formulation of feeds for all animals of different stages. We provide feed formulas with great accuracy and fast speed.`,
    jobDescription: `We want a software that can accurately calculate and formulate feed formula using feed ingredients provided by users accurately and fast.`,
    brandVisuals: [],
    // client
    clientContact: 0,
    clientName: "N/A",
    clientEmail: "N/A",
    clientLocation: "N/A",
  },
  {
    jobType: "software",
    brandName: "King's Fashion",
    brandServices: ["Tailoring", "Clothe Design"],
    brandContact: 9133146567,
    brandColors: ["#5805CE", "000000"],
    brandValues: ["Royality", "Creative", "Quality Delivery"],
    brandEmail: "",
    brandLocation: "Oyo State, Nigeria",
    brandVisuals: [],
    brandDescription: `King's Fashion is a textile brand that focuses on the design of both Nigeria Native dress and Western dress. We aim to making you feel the aura of royalty by giving you a quality, unique and eye-pleasing clothe design. `,
    jobDescription: `We want you to design for us a unique logo aiming at royalty.`,
    // client
    clientContactL: 0,
    clientName: "Uthman",
    clientEmail: "N/A",
    clientLocation: "Oyo State, Nigeria",
  },
  {
    jobType: "software",
    brandName: "Track-it",
    brandServices: ["Debt tracking", "Record Keeping"],
    brandContact: 0,
    brandColors: ["Blue", "White"],
    brandValues: ["Save", "Efficient"],
    brandEmail: "N/A",
    brandLocation: "N/A",
    brandDescription: `We are a debt tracking company that helps our customers track their debts and also record business information.`,
    jobDescription: `We want you to develop a software that track debt accurately.`,
    brandVisuals: [],
    // client
    clientContact: 0,
    clientName: "N/A",
    clientEmail: "N/A",
    clientLocation: "N/A",
  },
  {
    jobType: "design",
    brandName: "Folksy",
    brandServices: ["Jewellery Production"],
    brandContact: 0,
    brandColors: [],
    brandValues: ["Popular", "Homemade", "modern", "Delight"],
    brandEmail: "",
    brandLocation: "",
    brandDescription: `We are a little corner-shop that sells jewellery. Our main product standsout because of it's reputation and homemade feel. Our target audience is men. We want to convey a sense of delight while at the same time beign modern. `,
    jobDescription: `You must create the total branding package. This includes creating a appropriate brand name, a consistent visual system and of course a great logo.`,
    brandVisuals: [],
    // client
    clientContact: 0,
    clientName: "",
    clientEmail: "",
    clientLocation: "",
  },
  // {
  //   jobType: "software",
  //   brandName: "",
  //   brandServices: [],
  //   brandContact: 0,
  //   brandColors: [],
  //   brandValues: [],
  //   brandEmail: "",
  //   brandLocation: "",
  //   brandDescription: ` `,
  //   jobDescription: ``,
  //   brandVisuals: [],
  //   // client
  //   clientContact: 0,
  //   clientName: "",
  //   clientEmail: "",
  //   clientLocation: "",
  // },
];

export default briefStore